// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1grkaXa18U9DKE3_0z30al72zS6stBUc',
    appId: '1:50074894012:android:74e4bca7e940f74a6c9ab9',
    messagingSenderId: '50074894012',
    projectId: 'realsightmobile',
    storageBucket: 'realsightmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLoD6sih3xU4mY5rOzAqdksH1w5sqdsY',
    appId: '1:50074894012:ios:aafdf87f81bb8d166c9ab9',
    messagingSenderId: '50074894012',
    projectId: 'realsightmobile',
    storageBucket: 'realsightmobile.firebasestorage.app',
    androidClientId: '50074894012-2ccneptov4b0uh6r0bj4v845fvaqc1b5.apps.googleusercontent.com',
    iosClientId: '50074894012-rellav4scbgvdgvjvr8ipan0366jh7fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.realsightapp',
  );

}